ProTwo/AppTwo/urls.py
from django.conf.urls import url
from AppTwo import views

app_name = 'AppTwo'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^help/',views.help,name='help'),
    url(r'^users/',views.users,name='users'),
    url(r'^form/',views.form_name_view,name='form_name'),

    url(r'^base/',views.base,name='base'),
    url(r'^other/',views.other,name='other'),
    url(r'^url_templates/',views.url_templates,name='url_templates'),
]

ProTwo/ProTwo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from AppTwo import views

urlpatterns = [
    url(r'^',include('AppTwo.urls')),
    url(r'^admin/', admin.site.urls),
]

ProTwo/AppTwo/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete = models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete = models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class user(models.Model):
    first_name = models.CharField(max_length=264,unique=False)
    last_name = models.CharField(max_length=264,unique=False)
    email = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

ProTwo/AppTwo/forms.py
from django import forms
from AppTwo.models import user

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Your email one more time:')
    text = forms.CharField(widget=forms.Textarea)
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError("Email should match")

class FormUser(forms.ModelForm):
    class Meta:
        model = user
        fields = '__all__'

ProTwo/AppTwo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from AppTwo.models import AccessRecord,Topic,Webpage,user
from AppTwo.forms import FormName,FormUser
# Create your views here.

def index(request):
    context_dict = {'text':'some text','number':1234567}
    return render(request,'AppTwo/index.html',context=context_dict)

def help(request):
    helpdict = {'help_insert':'HELP PAGE'}
    return render(request,'AppTwo/help.html',context=helpdict)

def users(request):
    form = FormUser()
    if request.method == 'POST':
        form = FormUser(request.POST)
        if form.is_valid():
            print("VALID data!")
            print("Name: "+form.cleaned_data['first_name'])
            print("Email: "+form.cleaned_data['last_name'])
            print("Text: "+form.cleaned_data['email'])
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR ADDING USER')
    return render(request,'AppTwo/users.html',{'form':form})


def form_name_view(request):
    form = FormName()
    if request.method == 'POST':
        form = FormName(request.POST)
        if form.is_valid():
            print("VALID data!")
            print("Name: "+form.cleaned_data['name'])
            print("Email: "+form.cleaned_data['email'])
            print("Text: "+form.cleaned_data['text'])
    return render(request,'AppTwo/form_name.html',{'form':form})

def other(request):
    return render(request,'AppTwo/other.html')

def url_templates(request):
    return render(request,'AppTwo/url_templates.html')

def base(request):
    return render(request,'AppTwo/base.html')

ProTwo/templates/AppTwo/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">BRAND</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'AppTwo:index' %}">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'AppTwo:other' %}">Other</a>
        <a class="nav-item nav-link" href="{% url 'AppTwo:help' %}">Help</a>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block body_block %}
    <!-- Extension -->
    {% endblock %}
  </div>
</body>

</html>

ProTwo/templates/AppTwo/form_name.html
<html>

<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta charset="utf-8">
  <title>FORM PAGE</title>
</head>

<body>
  <div class="container">

    <form method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <button type="submit" class="btn btn-default">Submit</button>
    </form>


  </div>
</body>


</html>

ProTwo/templates/AppTwo/help.html
<html>
  <head>
    <meta charset="utf-8">
    <title>HELP PAGE</title>
  </head>
  <body>
    {{ help_insert }}

  </body>
</html>

ProTwo/templates/AppTwo/index.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}

    <h1>Index page and inheritance</h1>
    <h1>{{ text|cut:"so" }}</h1>
    <h1>{{ number|add:"1000000" }}</h1>
  {% endblock %}

ProTwo/templates/AppTwo/other.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}

    <h1>OTHER PAGE</h1>

  {% endblock %}

ProTwo/templates/AppTwo/url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>RELATIVE URL temp</h1>
    <a href="{% url 'AppTwo:other' %}">Blablala</a>
    <a href="{% url 'AppTwo:index' %}">Blablala222</a>
  </body>
</html>

ProTwo/templates/AppTwo/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Start page</title>
    <link rel="stylesheet" href="{% static 'css/mstyle.css' %}"/>
  </head>
  <body>
    <h1>Hello</h1>

    <div class="container">

      <h1>Please sign in here</h1>
      <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" name="btn btn-primary">Submit</button>
      </form>

    </div>

  </body>
</html>